spring.application.name=pointage-backend
server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/pointage_db

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Email Configuration (Required for password reset feature)
# For Gmail: Use App Password (https://support.google.com/accounts/answer/185833)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zakbenhamadi7@gmail.com
spring.mail.password=uvkh chlc nxhf iycc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Password Reset Token Expiration (in minutes)
password.reset.token.expiration=30

# Frontend Configuration
# frontend.reset-password-url=http://localhost:3000/reset-password
frontend.reset-password-url=http://localhost:5173/reset-password
